import React, { useCallback } from 'react';
import { FileCode } from 'lucide-react';
import { Button } from './Button';
import { Tooltip } from './Tooltip';
import type { Debate } from '../../types';

/**
 * ExportHTML — Generate a self-contained HTML page of a debate transcript.
 * The page includes inline CSS, is fully standalone, and can be shared.
 */

function generateDebateHTML(debate: Debate): string {
  const ROLE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
    proposition: { bg: '#EFF6FF', text: '#1D4ED8', border: '#BFDBFE' },
    opposition: { bg: '#FFF1F2', text: '#BE123C', border: '#FECDD3' },
    housemaster: { bg: '#FFFBEB', text: '#B45309', border: '#FDE68A' },
  };

  const PHASE_LABELS: Record<string, string> = {
    introduction: 'Introduction', opening: 'Opening Statement',
    transition: 'Transition', rebuttal: 'Rebuttal',
    'cross-examination': 'Cross-Examination',
    closing: 'Closing Statement', verdict: 'Verdict',
  };

  const turnsHTML = debate.turns.map((turn, i) => {
    const debater = debate.debaters.find((d) => d.id === turn.debaterId);
    const role = debater?.position ?? 'proposition';
    const colors = ROLE_COLORS[role] ?? ROLE_COLORS.proposition;
    const phase = PHASE_LABELS[turn.phase] ?? turn.phase;
    const wordCount = turn.content.split(/\s+/).filter(Boolean).length;

    return `
      <div class="turn" style="border-left: 4px solid ${colors.border}; background: ${colors.bg}; padding: 16px 20px; border-radius: 8px; margin-bottom: 16px;">
        <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
          <span style="background: ${colors.border}; color: ${colors.text}; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; text-transform: uppercase;">${role}</span>
          <span style="font-weight: 600; color: #1F2937;">${turn.debaterName}</span>
          <span style="color: #9CA3AF; font-size: 12px;">Step ${i + 1} &mdash; ${phase}</span>
          <span style="color: #9CA3AF; font-size: 11px; margin-left: auto;">${wordCount} words</span>
        </div>
        <div style="color: #374151; line-height: 1.6; white-space: pre-wrap;">${escapeHtml(turn.content)}</div>
        ${turn.citations && turn.citations.length > 0 ? `
          <div style="margin-top: 12px; padding-top: 8px; border-top: 1px solid ${colors.border}; font-size: 12px; color: #6B7280;">
            <strong>Citations:</strong> ${turn.citations.map((c) => `<a href="${escapeHtml(c.url)}" target="_blank" style="color: ${colors.text};">${escapeHtml(c.title || c.url)}</a>`).join(', ')}
          </div>
        ` : ''}
        ${turn.fallacies && turn.fallacies.length > 0 ? `
          <div style="margin-top: 8px; font-size: 12px;">
            ${turn.fallacies.map((f) => `<span style="background: #FEF2F2; color: #991B1B; padding: 2px 8px; border-radius: 10px; font-size: 11px; margin-right: 4px;">${escapeHtml(f.name)}</span>`).join('')}
          </div>
        ` : ''}
      </div>
    `;
  }).join('');

  const debatersList = debate.debaters.map((d) => {
    const colors = ROLE_COLORS[d.position] ?? ROLE_COLORS.proposition;
    return `<span style="background: ${colors.border}; color: ${colors.text}; padding: 4px 12px; border-radius: 16px; font-size: 13px; font-weight: 500;">${d.name} (${d.position}) &mdash; ${d.model.displayName}</span>`;
  }).join(' ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Debate: ${escapeHtml(debate.topic)} — DebateForge</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #F9FAFB; color: #111827; max-width: 800px; margin: 0 auto; padding: 24px 16px; }
    h1 { font-size: 24px; margin-bottom: 8px; }
    .meta { color: #6B7280; font-size: 14px; margin-bottom: 16px; }
    .debaters { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 24px; }
    .divider { height: 1px; background: #E5E7EB; margin: 24px 0; }
    .footer { text-align: center; color: #9CA3AF; font-size: 12px; margin-top: 32px; }
    a { text-decoration: none; } a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>${escapeHtml(debate.topic)}</h1>
  <div class="meta">
    ${debate.format.name} &bull; ${debate.turns.length} turns &bull; ${new Date(debate.createdAt).toLocaleDateString()}
  </div>
  <div class="debaters">${debatersList}</div>
  <div class="divider"></div>
  ${turnsHTML}
  <div class="divider"></div>
  <div class="footer">
    Generated by DebateForge &mdash; AI-Powered Debate Arena
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export const ExportHTMLButton: React.FC<{ debate: Debate }> = ({ debate }) => {
  const handleExport = useCallback(() => {
    const html = generateDebateHTML(debate);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `debate-${debate.topic.slice(0, 40).replace(/[^a-zA-Z0-9]/g, '-')}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [debate]);

  return (
    <Tooltip content="Export as shareable HTML page">
      <Button variant="ghost" size="sm" onClick={handleExport} icon={<FileCode className="h-4 w-4" />}>
        HTML
      </Button>
    </Tooltip>
  );
};

export default ExportHTMLButton;
