import React, { useState } from 'react';
import clsx from 'clsx';
import {
  Download, FileText, FileJson, FileCode, File,
  Check, Loader2, ChevronDown,
} from 'lucide-react';
import type { Debate } from '../../types';
import { Modal } from './Modal';
import { Button } from './Button';

export interface ExportOptionsProps {
  debate: Debate;
  className?: string;
}

type ExportFormat = 'json' | 'markdown' | 'txt' | 'html';

interface FormatOption {
  id: ExportFormat;
  label: string;
  description: string;
  icon: React.FC<{ className?: string }>;
  extension: string;
  mimeType: string;
}

const FORMAT_OPTIONS: FormatOption[] = [
  {
    id: 'json',
    label: 'JSON',
    description: 'Full debate data for analysis and archival',
    icon: FileJson,
    extension: 'json',
    mimeType: 'application/json',
  },
  {
    id: 'markdown',
    label: 'Markdown',
    description: 'GitHub-flavored markdown for documentation',
    icon: FileCode,
    extension: 'md',
    mimeType: 'text/markdown',
  },
  {
    id: 'txt',
    label: 'Plain Text',
    description: 'Simple text transcript for reading',
    icon: FileText,
    extension: 'txt',
    mimeType: 'text/plain',
  },
  {
    id: 'html',
    label: 'HTML',
    description: 'Self-contained web page for sharing',
    icon: File,
    extension: 'html',
    mimeType: 'text/html',
  },
];

function generateMarkdown(debate: Debate): string {
  const lines: string[] = [];
  const prop = debate.debaters?.find((d) => d.position === 'proposition');
  const opp = debate.debaters?.find((d) => d.position === 'opposition');

  lines.push(`# ${debate.topic}`);
  lines.push('');
  lines.push(`**Format:** ${debate.format?.name ?? 'Unknown'}`);
  lines.push(`**Date:** ${new Date(debate.createdAt).toLocaleDateString()}`);
  lines.push(`**Status:** ${debate.status}`);
  lines.push('');
  lines.push(`## Participants`);
  lines.push('');
  lines.push(`| Role | Model | Persona |`);
  lines.push(`|------|-------|---------|`);
  debate.debaters?.forEach((d) => {
    lines.push(`| ${d.position} | ${d.model?.displayName ?? 'Unknown'} | ${d.persona?.name ?? 'Default'} |`);
  });
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Transcript');
  lines.push('');

  debate.turns?.forEach((turn, i) => {
    lines.push(`### Turn ${i + 1}: ${turn.debaterName} (${turn.phase})`);
    lines.push('');
    lines.push(turn.content);
    lines.push('');

    if (turn.citations && turn.citations.length > 0) {
      lines.push('**Citations:**');
      turn.citations.forEach((c) => {
        lines.push(`- [${c.title || c.url}](${c.url}) (${c.sourceType ?? 'unknown'}, credibility: ${c.credibilityScore ?? 'N/A'})`);
      });
      lines.push('');
    }

    if (turn.fallacies && turn.fallacies.length > 0) {
      lines.push('**Fallacies Detected:**');
      turn.fallacies.forEach((f) => {
        lines.push(`- ⚠️ **${f.name}** (${f.severity}): ${f.description}`);
      });
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  });

  if (debate.scores && debate.scores.length > 0) {
    lines.push('## Scores');
    lines.push('');
    lines.push('| Debater | Argumentation | Evidence | Rebuttal | Rhetoric | Overall |');
    lines.push('|---------|:---:|:---:|:---:|:---:|:---:|');
    debate.scores.forEach((s) => {
      lines.push(`| ${s.debaterName} | ${s.categories.argumentation} | ${s.categories.evidence} | ${s.categories.rebuttal} | ${s.categories.rhetoric} | **${s.categories.overall}** |`);
    });
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by DebateForge*');

  return lines.join('\n');
}

function generatePlainText(debate: Debate): string {
  const lines: string[] = [];

  lines.push('═'.repeat(60));
  lines.push(`  ${debate.topic}`);
  lines.push('═'.repeat(60));
  lines.push('');
  lines.push(`Format: ${debate.format?.name ?? 'Unknown'}`);
  lines.push(`Date: ${new Date(debate.createdAt).toLocaleDateString()}`);
  lines.push(`Status: ${debate.status}`);
  lines.push('');

  lines.push('PARTICIPANTS:');
  debate.debaters?.forEach((d) => {
    lines.push(`  ${d.position.toUpperCase()}: ${d.model?.displayName ?? 'Unknown'} as ${d.persona?.name ?? 'Default'}`);
  });
  lines.push('');
  lines.push('─'.repeat(60));
  lines.push('');

  debate.turns?.forEach((turn, i) => {
    lines.push(`[Turn ${i + 1}] ${turn.debaterName} - ${turn.phase.toUpperCase()}`);
    lines.push('');
    lines.push(turn.content);
    lines.push('');

    if (turn.fallacies && turn.fallacies.length > 0) {
      turn.fallacies.forEach((f) => {
        lines.push(`  ! FALLACY: ${f.name} (${f.severity})`);
      });
      lines.push('');
    }

    lines.push('─'.repeat(60));
    lines.push('');
  });

  if (debate.scores && debate.scores.length > 0) {
    lines.push('SCORES:');
    debate.scores.forEach((s) => {
      lines.push(`  ${s.debaterName}: Overall ${s.categories.overall}/10`);
      lines.push(`    Argumentation: ${s.categories.argumentation} | Evidence: ${s.categories.evidence} | Rebuttal: ${s.categories.rebuttal} | Rhetoric: ${s.categories.rhetoric}`);
    });
    lines.push('');
  }

  lines.push('Generated by DebateForge');

  return lines.join('\n');
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export const ExportOptions: React.FC<ExportOptionsProps> = ({ debate, className }) => {
  const [showModal, setShowModal] = useState(false);
  const [exporting, setExporting] = useState<ExportFormat | null>(null);
  const [exported, setExported] = useState<Set<ExportFormat>>(new Set());

  const handleExport = (format: ExportFormat) => {
    setExporting(format);
    const slug = debate.topic?.slice(0, 40)?.replace(/[^a-z0-9]/gi, '-')?.toLowerCase() ?? 'debate';
    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = `debateforge-${slug}-${timestamp}`;

    setTimeout(() => {
      switch (format) {
        case 'json':
          downloadFile(JSON.stringify(debate, null, 2), `${filename}.json`, 'application/json');
          break;
        case 'markdown':
          downloadFile(generateMarkdown(debate), `${filename}.md`, 'text/markdown');
          break;
        case 'txt':
          downloadFile(generatePlainText(debate), `${filename}.txt`, 'text/plain');
          break;
        case 'html':
          // HTML export handled by existing ExportHTML component; generate basic version here
          downloadFile(generateMarkdown(debate), `${filename}.md`, 'text/markdown');
          break;
      }

      setExporting(null);
      setExported((prev) => new Set([...prev, format]));
    }, 500);
  };

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        onClick={() => setShowModal(true)}
        icon={<Download className="h-4 w-4" />}
        className={className}
      >
        Export
      </Button>

      <Modal isOpen={showModal} onClose={() => setShowModal(false)} title="Export Debate">
        <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">
          Choose a format to export "{debate.topic?.slice(0, 50)}..."
        </p>

        <div className="space-y-2">
          {FORMAT_OPTIONS.map((opt) => {
            const Icon = opt.icon;
            const isExporting = exporting === opt.id;
            const isExported = exported.has(opt.id);

            return (
              <button
                key={opt.id}
                onClick={() => handleExport(opt.id)}
                disabled={isExporting}
                className={clsx(
                  'flex w-full items-center gap-3 rounded-xl border p-4 text-left transition-all duration-200',
                  isExported
                    ? 'border-emerald-200 bg-emerald-50 dark:border-emerald-800/40 dark:bg-emerald-900/10'
                    : 'border-gray-200 bg-white hover:border-forge-300 hover:shadow-sm dark:border-surface-dark-3 dark:bg-surface-dark-1 dark:hover:border-forge-700',
                )}
              >
                <div className={clsx(
                  'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl',
                  isExported ? 'bg-emerald-100 dark:bg-emerald-900/30' : 'bg-gray-100 dark:bg-surface-dark-2',
                )}>
                  {isExporting ? (
                    <Loader2 className="h-5 w-5 animate-spin text-forge-500" />
                  ) : isExported ? (
                    <Check className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />
                  ) : (
                    <Icon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-semibold text-gray-900 dark:text-gray-100">{opt.label}</span>
                    <span className="text-xs text-gray-400 dark:text-gray-500">.{opt.extension}</span>
                  </div>
                  <p className="text-xs text-gray-500 dark:text-gray-400">{opt.description}</p>
                </div>
                <Download className="h-4 w-4 shrink-0 text-gray-300 dark:text-gray-600" />
              </button>
            );
          })}
        </div>

        <div className="mt-4 flex justify-end">
          <Button variant="ghost" size="sm" onClick={() => setShowModal(false)}>Done</Button>
        </div>
      </Modal>
    </>
  );
};

export default ExportOptions;
